Chapter6
MikhYur1991/data-devops-test pull request #6
Opened 2021-12-16 21:26 UTC by MikhYur1991

@Cakemanator comment me

2021-12-17 13:18 UTC, Cakemanator requested changes

2021-12-17 13:18 UTC, Cakemanator commented on ch6_ex1
> +IdentityFile %d/.ssh/hw-5
Это весь конфиг? Не вижу в нем директивы Host

2021-12-17 13:18 UTC, Cakemanator commented on ch6_ex1
> +[guest1@localhost ~]$ ssh -L 0.0.0.0:8080:webserver:80 remotehost
Команда верная, возможно что-то просочилось в конфиг
Попробовал `ssh -L 0.0.0.0:8080:172.31.45.237:80 Mikhail_Mikhailovskiy@18.221.144.175`, форвардинг отработал

2021-12-23 04:27 UTC, MikhYur1991 commented on ch6_ex1
> +IdentityFile %d/.ssh/hw-5
дело в том, что ранее была сделана запись в /etc/hosts (есть в начале задания), поэтому посчитал что нет смысла делать аналогичную по сути запись для конкретного сервиса

2021-12-23 10:13 UTC, Cakemanator commented on ch6_ex1
> +IdentityFile %d/.ssh/hw-5
Эти записи относятся к разным сервисам, поэтому в ssh config нужно добавить host
https://linuxize.com/post/using-the-ssh-config-file/

2021-12-24 05:42 UTC, MikhYur1991 commented on ch6_ex1
> +IdentityFile %d/.ssh/hw-5
поправил, но на практике не проверял - отваливается по таймауту отчего то

2021-12-24 05:44 UTC, Cakemanator commented on ch6_ex1
> +IdentityFile %d/.ssh/hw-5
Виртуалки выключены после дедлайна, можно у себя локально поднять виртуалки, поставить там nginx и проверить самостоятельно

2021-12-24 06:22 UTC, MikhYur1991 commented on ch6_ex1
> +IdentityFile %d/.ssh/hw-5
ок, мержу в таком случае

2021-12-24 06:23 UTC, merged